
using SkyCars.Core.DomainEntity.User;
using SkyCars.Data.Migrations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SkyCars.Data.Migration
{
    [MigrationInfo("2022-08-30 09:17:12", "Initialize base Schema")]
    public class BaseInitMigration : FluentMigrator.Migration
    {
        public override void Up()
        {
            #region :: User Schema ::
            Create
                .Table(nameof(User)).WithDescription("User master") //can also pass custom name e.g. .Table("ProductMst")
                .WithColumn(nameof(User.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Autogenerated unique identifier")
                .WithColumn(nameof(User.UserName)).AsAnsiString(100).NotNullable().WithColumnDescription("User name")
                .WithColumn(nameof(User.Password)).AsAnsiString(100).NotNullable().WithColumnDescription("User Password")
                .WithColumn(nameof(User.FirstName)).AsAnsiString(100).NotNullable().WithColumnDescription("First name")
                .WithColumn(nameof(User.LastName)).AsAnsiString(100).NotNullable().WithColumnDescription("Last name")
                .WithColumn(nameof(User.Email)).AsAnsiString(100).NotNullable().WithColumnDescription("User Email")
                .WithColumn(nameof(User.ContactNumber)).AsAnsiString(100).NotNullable().WithColumnDescription("User Contact Number")
                .WithColumn(nameof(User.CreatedDate)).AsDateTime().NotNullable().WithColumnDescription("Entry Date")
                .WithColumn(nameof(User.UpdatedDate)).AsDateTime().Nullable().WithColumnDescription("Entry Update Date")
                .WithColumn(nameof(User.IsDelete)).AsBoolean().Nullable().WithColumnDescription("For delete").WithDefaultValue(true);
            #endregion

            Execute.Script("DbScriptMigration/UserDefaultRecored.sql");
            Execute.Script("DbScriptMigration/logdbschema.sql");
        }

        public override void Down()
        {

        }
    }
}
