using SkyCars.Core.DomainEntity.City;
using SkyCars.Data.Migrations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SkyCars.Data.Migration
{
    [MigrationInfo("2022-08-31 02:20:12", "City Schema")]
    public class CityInitMigration : FluentMigrator.Migration
    {
        public override void Up()
        {
            #region :: City Schema ::
            Create
                .Table(nameof(City)).WithDescription("User master") //can also pass custom name e.g. .Table("ProductMst")
                .WithColumn(nameof(City.Id)).AsInt32().PrimaryKey().NotNullable().Identity().WithColumnDescription("Autogenerated unique identifier")
                .WithColumn(nameof(City.CityName)).AsAnsiString(100).NotNullable().WithColumnDescription("User name")
                .WithColumn(nameof(City.CreatedDate)).AsDateTime().NotNullable().WithColumnDescription("Entry Date")
                .WithColumn(nameof(City.UpdatedDate)).AsDateTime().NotNullable().WithColumnDescription("Entry Update Date")
                .WithColumn(nameof(City.IsDelete)).AsBoolean().Nullable().WithColumnDescription("For delete").WithDefaultValue(true);
            #endregion

            Execute.Script("DbScriptMigration/UserDefaultRecored.sql");
            Execute.Script("DbScriptMigration/logdbschema.sql");
        }
        public override void Down()
        {
            
        }

       
    }
}
